---
title: My Journey To Transparency And Reproducibility
summary: A journey towards a more transparent and reproducible work environment using Docker and `renv`.
abstract: In this talk, I (Mickaël Canouil) will chronicle my journey towards a more transparent and reproducible work environment. I will talk about the changes and improvements that I have implemented in my team, detailing the transition of infrastructure used when I arrived to an infrastructure using Docker and and the {renv} R package.

all_day: false

date: "2021-04-15T19:00:00Z"
# date_end: "2021-04-15"
publishDate: "2021-04-15"

event: R Lille Meetup
event_url: https://www.meetup.com/R-Lille/events/277031496/
location: Online (Lille, France)
# address:
#   # street: 450 Serra Mall
#   city: Lille
#   postcode: '59000'
#   country: France

featured: false
image:
  focal_point: Right

projects: []

tags:
  - R
  - docker
  - renv
  - reproducibility
  - meetup
  - english
  
links:  
- icon: file-alt
  icon_pack: far
  name: Slides
  url: https://m.canouil.fr/slides/20210415-journey-reproducibility/
- icon: film
  icon_pack: fas
  name: Video
  url: https://youtu.be/1CE8crjkwYY
- icon: github
  icon_pack: fab
  name: Code
  url: https://github.com/mcanouil/journey-reproducibility
  
# url_code: ""
# url_pdf: ""
# url_slides: ""
# url_video: ""
---

```{r setup, include = FALSE}
url_slides <- "https://m.canouil.fr/slides/20210415-journey-reproducibility/"
url_video <- "https://www.youtube.com/embed/1CE8crjkwYY"
```

```{r, include = FALSE, eval = FALSE}
library(magick)
library(here)
library(chromote)
library(glue)

thumb <- "featured.png"
index_html <- url_slides

if (!file.exists(thumb)) {
  web_browser <- suppressMessages(try(chromote::ChromoteSession$new(), silent = TRUE))
  if (inherits(web_browser, "try-error") && Sys.info()[["sysname"]] == "Windows") {
    edge_path <- "C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe"
    if (file.exists(edge_path)) {
      Sys.setenv(CHROMOTE_CHROME = edge_path)
      web_browser <- chromote::ChromoteSession$new()
    } else {
      stop('Please set Sys.setenv(CHROMOTE_CHROME = "Path/To/Chrome")')
    }
  }
  web_browser$Page$navigate(index_html, wait_ = FALSE)
  page_browser <- web_browser$Page$loadEventFired()
  web_browser$screenshot(
    filename = thumb,
    selector = "div.remark-slide-scaler",
    scale = 2
  )
  web_browser$close()
  
  resize <- function(path_in, path_out) {
    image <- image_read(path_in)
    image <- image_resize(image, "1920x")
    image_write(image, path_out)
  }
  resize(thumb, thumb)
}
```

```{r, eval = !is.null(url_video), results = "asis", echo = FALSE, include = TRUE}
cat(
'<div class="embed-responsive embed-responsive-16by9">
  <iframe class="embed-responsive-item" src="', url_video, '" allowfullscreen></iframe>
</div>',
sep = ""
)
```

```{r, eval = !is.null(url_slides), results = "asis", echo = FALSE, include = TRUE}
cat(
'<div class="embed-responsive embed-responsive-16by9 xaringan">
  <iframe class="embed-responsive-item" src="', url_slides, '" allowfullscreen></iframe>
</div>',
sep = ""
)
```
