project:
  type: default
  output-dir: ../output

filters:
  - prism
  - offset-headings
  - cascade

extensions:
  prism:
    warn-on-drop: true
  offset-headings:
    quarto-shift-warning: false

format:
  html:
    output-file: demo.html
    embed-resources: true
    toc: true
  typst:
    output-file: demo.pdf
    shift-heading-level-by: 0
  revealjs:
    output-file: demo-slides.html
    embed-resources: true
