title: Mickaël Canouil's Website
theme: "starter-academic"
baseURL: http://mickael.canouil.fr/
languageCode: en-uk
googleAnalytics: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
markup:
  goldmark:
    renderer:
      unsafe: true
