title: R & MC
theme: "starter-academic"
baseURL: 'mickael.canouil.fr'
languageCode: en-gb
googleAnalytics: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
markup:
  goldmark:
    renderer:
      unsafe: true
publishDir: "/www"
