--- @license MIT
--- @copyright 2026 Mickaël Canouil
--- @author Mickaël Canouil
--
-- Keep `mailto:` addresses out of the rendered HTML.
--
-- Every `mailto:` link becomes an `<a>` whose target is base64 and whose href
-- is a same-page anchor, so neither the address nor the `mailto:` scheme is
-- present in the source for an address harvester to match. The companion
-- script `assets/scripts/email.html` restores the real href on load, using the
-- `window.mcDecodeB64` helper from `assets/scripts/base64.html`.
--
-- Quarto's own `email-obfuscation` is not usable here: `javascript` mode
-- HTML-escapes the whole anchor, which printed the `iconify-icon` tags of the
-- mail buttons as literal text, and `references` mode escapes inline markup
-- the same way. Neither covers the links generated by the `about` block.
--
-- The link keeps its contents, so icons and labels survive, and it stays
-- focusable without JavaScript. A link that used the address as its own label
-- keeps a readable `name [at] example [dot] com` form, so a reader without
-- JavaScript can still retype it.
--
-- This does not reach the links of the `about` block: Quarto builds those from
-- document metadata before the Lua pipeline runs, so they are absent from both
-- the AST and `Meta` by the time any filter sees the document. Write those
-- hrefs as `#mc-email-<base64>` instead; `assets/scripts/email.html` restores
-- them from the href.

local BASE64_ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"

--- Encode a string as base64.
--- Pandoc's Lua standard library has no base64 encoder, and the payload here is
--- a handful of ASCII addresses, so a short local implementation is enough.
--- @param input string
--- @return string
local function base64_encode(input)
  local bytes = { string.byte(input, 1, #input) }
  local out = {}
  for index = 1, #bytes, 3 do
    local b1, b2, b3 = bytes[index], bytes[index + 1], bytes[index + 2]
    local chunk = b1 * 65536 + (b2 or 0) * 256 + (b3 or 0)
    local c1 = math.floor(chunk / 262144) % 64
    local c2 = math.floor(chunk / 4096) % 64
    local c3 = math.floor(chunk / 64) % 64
    local c4 = chunk % 64
    out[#out + 1] = BASE64_ALPHABET:sub(c1 + 1, c1 + 1)
    out[#out + 1] = BASE64_ALPHABET:sub(c2 + 1, c2 + 1)
    out[#out + 1] = b2 and BASE64_ALPHABET:sub(c3 + 1, c3 + 1) or "="
    out[#out + 1] = b3 and BASE64_ALPHABET:sub(c4 + 1, c4 + 1) or "="
  end
  return table.concat(out)
end

--- Spell an address out so a reader without JavaScript can still retype it.
--- @param address string address without the `mailto:` scheme
--- @return string
local function spell_out(address)
  return (address:gsub("@", " [at] "):gsub("%.", " [dot] "))
end

--- Replace the visible address, when a link uses it as its own label.
--- @param content table inline elements
--- @param address string
--- @return table
local function mask_visible_address(content, address)
  return content:walk({
    Str = function(el)
      if el.text:find(address, 1, true) then
        return pandoc.Str((el.text:gsub(address, spell_out(address), 1)))
      end
    end,
  })
end

function Link(el)
  if not FORMAT:match("html") then
    return nil
  end

  local address = el.target:match("^mailto:(.+)$")
  if not address then
    return nil
  end

  -- Strip any query string (`?subject=`) before encoding; the script appends
  -- what it decodes verbatim, so the whole target is encoded as one payload.
  el.attributes["data-mc-email"] = base64_encode(address)
  el.classes:insert("mc-email")
  el.target = "#"
  el.content = mask_visible_address(el.content, (address:gsub("%?.*$", "")))

  return el
end
