name: "quarto-render"
description: "Build and push a Quarto rendered project to GitHub."

inputs:
  version:
    description: "The Quarto release version type."
    required: true
    default: pre-release
  
runs:
  using: "composite"
  steps:
    - uses: r-lib/actions/setup-pandoc@v2
    - uses: r-lib/actions/setup-r@v2
    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
        packages:
          any::knitr
          any::rmarkdown
          any::downlit
          any::xml2
          any::webshot2
    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2
      with:
        version: ${{ inputs.version }}
    - name: Render Quarto Project
      uses: quarto-dev/quarto-actions/render@v2
