---
title: |
    "Débuter" avec R en Commençant par le Début ... (French)
summary: |
    Tips and advices to start well with R (and RStudio).
abstract: |
    Vous souhaitez démarrer avec de bonnes bases ?
    Vous suspectez que vous n'avez pas que des bonnes pratiques/habitudes ?
    Vous aimeriez améliorer ou modifier votre pratique de R, pour être plus efficace et plus autonome ?
    Vous ignorez ce que sont les fichiers .Rdata, .rds, .R, .Rmd, .Renviron et/ou .Rprofile ?
    Vous maitrisez les commandes rm(list = ls()) et setwd() ?
    
    Ce MeetUp vise à donner quelques trucs et astuces autour de R et de l'IDE Rstudio, ainsi qu'ouvrir la discussion sur quelques "règles/conventions" de bonnes pratiques dans un objectif de reproductibilité.

all_day: false

date: "2021-01-07T12:00:00Z"
# date_end: "2021-01-07
publishDate: "2021-01-07"

event: R Lille Meetup
event_url: https://www.meetup.com/R-Lille/events/273159362/
location: Faculté de Médecine de Lille - Pôle Recherche
address:
  street: 1, Place de Verdun
  city: Lille
  postcode: '59000'
  country: France

featured: false
image:
  focal_point: Right

projects: []

tags:
  - R
  - setup
  - tips
  - project
  - good practices
  - french

links:  
- icon: file-alt
  icon_pack: far
  name: Slides
  url: https://m.canouil.fr/slides/20201007-r-startup/
- icon: github
  icon_pack: fab
  name: Code
  url: https://github.com/mcanouil/rstartup
  
# url_code: ""
# url_pdf: ""
# url_slides: ""
# url_video: ""
---

```{r setup, include = FALSE}
url_slides <- "https://m.canouil.fr/slides/20201007-r-startup/"
```

```{r, include = FALSE, eval = FALSE}
library(magick)
library(here)
library(chromote)
library(glue)

thumb <- "featured.png"
index_html <- url_slides

if (!file.exists(thumb)) {
  web_browser <- suppressMessages(try(chromote::ChromoteSession$new(), silent = TRUE))
  if (inherits(web_browser, "try-error") && Sys.info()[["sysname"]] == "Windows") {
    edge_path <- "C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe"
    if (file.exists(edge_path)) {
      Sys.setenv(CHROMOTE_CHROME = edge_path)
      web_browser <- chromote::ChromoteSession$new()
    } else {
      stop('Please set Sys.setenv(CHROMOTE_CHROME = "Path/To/Chrome")')
    }
  }
  web_browser$Page$navigate(index_html, wait_ = FALSE)
  page_browser <- web_browser$Page$loadEventFired()
  web_browser$screenshot(
    filename = thumb,
    selector = "div.remark-slide-scaler",
    scale = 2
  )
  web_browser$close()
  
  resize <- function(path_in, path_out) {
    image <- image_read(path_in)
    image <- image_resize(image, "1920x")
    image_write(image, path_out)
  }
  resize(thumb, thumb)
}
```

```{r, eval = !is.null(url_slides), results = "asis", echo = FALSE, include = TRUE}
cat(
'<div class="embed-responsive embed-responsive-16by9 xaringan">
  <iframe class="embed-responsive-item" src="', url_slides, '" allowfullscreen></iframe>
</div>',
sep = ""
)
```
