project:
  type: default
  output-dir: ../slides
  lib-dir: ../slides/lib
  pre-render:
    - rm -rf ../slides
  render:
    - "demo-*.qmd"

author: "Mickaël Canouil, *Ph.D.*"
institute: "mickael.canouil.fr"
date: today
format:
  revealjs:
    controls: true
    loop: true
